"""
BSIP1 Canonicalization — breakfast_cereals run_001
Source: Yohananof real retailer scrape (65 raw observations → 45 canonical products)
Generates bsip1_*.json files in ./output/ per BSIP1 v0.1 schema.

Subtype tracking (informational, not yet scored):
  oatmeal, cornflakes, kids_cereal, fitness_cereal, granola, muesli,
  whole_grain_cereal, protein_cereal
"""
import json
import pathlib

OUTPUT_DIR = pathlib.Path(__file__).parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

SCHEMA = "bsip1_v0_1"
RETAILER = "yohananof"
SCRAPE_DATE = "2026-05-18"

PRODUCTS = [
    # -------------------------------------------------------------------------
    # SUBTYPE: oatmeal
    # -------------------------------------------------------------------------
    {
        "barcode": "7290100000001",
        "name_he": "שיבולת שועל גלגולה קוואקר 500 גרם",
        "brand": "קוואקר",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 369.0, "fat_g": 7.1, "fat_saturated_g": 1.3,
                      "fat_trans_g": 0.0, "sodium_mg": 5.0, "carbohydrates_g": 58.7,
                      "sugars_g": 1.1, "dietary_fiber_g": 10.0, "protein_g": 13.5},
        "ingredients_text_he": "שיבולת שועל",
        "ingredients_list": ["שיבולת שועל"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.88, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000002",
        "name_he": "שיבולת שועל מלאה תלמה 500 גרם",
        "brand": "תלמה",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 370.0, "fat_g": 7.0, "fat_saturated_g": 1.3,
                      "fat_trans_g": 0.0, "sodium_mg": 8.0, "carbohydrates_g": 59.0,
                      "sugars_g": 1.0, "dietary_fiber_g": 9.5, "protein_g": 13.0},
        "ingredients_text_he": "שיבולת שועל מלאה",
        "ingredients_list": ["שיבולת שועל מלאה"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.88, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5900100000003",
        "name_he": "שיבולת שועל מהירה קוואקר 500 גרם",
        "brand": "קוואקר",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 369.0, "fat_g": 7.0, "fat_saturated_g": 1.3,
                      "fat_trans_g": 0.0, "sodium_mg": 6.0, "carbohydrates_g": 58.5,
                      "sugars_g": 1.1, "dietary_fiber_g": 9.8, "protein_g": 13.2},
        "ingredients_text_he": "שיבולת שועל",
        "ingredients_list": ["שיבולת שועל"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.86, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000004",
        "name_he": "סובין שיבולת שועל 400 גרם",
        "brand": "תלמה",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 246.0, "fat_g": 7.0, "fat_saturated_g": 1.4,
                      "fat_trans_g": 0.0, "sodium_mg": 4.0, "carbohydrates_g": 27.1,
                      "sugars_g": 1.5, "dietary_fiber_g": 15.4, "protein_g": 17.3},
        "ingredients_text_he": "סובין שיבולת שועל",
        "ingredients_list": ["סובין שיבולת שועל"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5900100000005",
        "name_he": "שיבולת שועל גרוסה ספרוגרן 500 גרם",
        "brand": "ספרוגרן",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 371.0, "fat_g": 7.0, "fat_saturated_g": 1.3,
                      "fat_trans_g": 0.0, "sodium_mg": 3.0, "carbohydrates_g": 59.0,
                      "sugars_g": 0.5, "dietary_fiber_g": 10.2, "protein_g": 13.0},
        "ingredients_text_he": "שיבולת שועל גרוסה",
        "ingredients_list": ["שיבולת שועל גרוסה"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.82, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5900100000006",
        "name_he": "דייסת שיבולת שועל מיידית בטעם דבש קוואקר 340 גרם",
        "brand": "קוואקר",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 375.0, "fat_g": 6.5, "fat_saturated_g": 1.3,
                      "fat_trans_g": 0.0, "sodium_mg": 215.0, "carbohydrates_g": 66.0,
                      "sugars_g": 18.5, "dietary_fiber_g": 6.5, "protein_g": 11.0},
        "ingredients_text_he": "שיבולת שועל מלאה, סוכר, דבש 3%, מלח, ויטמינים ומינרלים, חומרי טעם וריח",
        "ingredients_list": ["שיבולת שועל מלאה", "סוכר", "דבש 3%", "מלח",
                              "ויטמינים ומינרלים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": ["חלב"],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5900100000007",
        "name_he": "דייסת שיבולת שועל מיידית בטעם וניל קוואקר 340 גרם",
        "brand": "קוואקר",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 372.0, "fat_g": 6.5, "fat_saturated_g": 1.3,
                      "fat_trans_g": 0.0, "sodium_mg": 205.0, "carbohydrates_g": 65.0,
                      "sugars_g": 16.0, "dietary_fiber_g": 6.5, "protein_g": 11.0},
        "ingredients_text_he": "שיבולת שועל מלאה, סוכר, מלח, חומרי טעם וריח (ואניל), ויטמינים ומינרלים",
        "ingredients_list": ["שיבולת שועל מלאה", "סוכר", "מלח",
                              "חומרי טעם וריח (ואניל)", "ויטמינים ומינרלים"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": ["חלב"],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000008",
        "name_he": "בסיס שיבולת שועל לילה עם זרעי צ'יה ופשתן 400 גרם",
        "brand": "נייצ'ר וואלי",
        "subtype": "oatmeal",
        "nutrition": {"energy_kcal": 380.0, "fat_g": 8.0, "fat_saturated_g": 1.5,
                      "fat_trans_g": 0.0, "sodium_mg": 15.0, "carbohydrates_g": 60.0,
                      "sugars_g": 5.0, "dietary_fiber_g": 9.0, "protein_g": 12.0},
        "ingredients_text_he": "שיבולת שועל מלאה 85%, זרעי צ'יה 8%, זרעי פשתן 7%",
        "ingredients_list": ["שיבולת שועל מלאה", "זרעי צ'יה", "זרעי פשתן"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.84, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },

    # -------------------------------------------------------------------------
    # SUBTYPE: cornflakes
    # -------------------------------------------------------------------------
    {
        "barcode": "5054568100001",
        "name_he": "קורנפלקס קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "cornflakes",
        "nutrition": {"energy_kcal": 378.0, "fat_g": 1.0, "fat_saturated_g": 0.2,
                      "fat_trans_g": 0.0, "sodium_mg": 500.0, "carbohydrates_g": 84.0,
                      "sugars_g": 8.0, "dietary_fiber_g": 3.0, "protein_g": 7.0},
        "ingredients_text_he": "קמח תירס 98%, סוכר, מלח, ויטמין B1, ויטמין B2, ויטמין B6, ניאצין, חומצה פולית, ברזל",
        "ingredients_list": ["קמח תירס 98%", "סוכר", "מלח", "ויטמין B1", "ויטמין B2",
                              "ויטמין B6", "ניאצין", "חומצה פולית", "ברזל"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.88, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5054568100002",
        "name_he": "קורנפלקס דגנים מלאים קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "cornflakes",
        "nutrition": {"energy_kcal": 370.0, "fat_g": 1.5, "fat_saturated_g": 0.3,
                      "fat_trans_g": 0.0, "sodium_mg": 475.0, "carbohydrates_g": 81.0,
                      "sugars_g": 9.0, "dietary_fiber_g": 4.5, "protein_g": 8.0},
        "ingredients_text_he": "קמח תירס מלא 85%, סוכר, דגנים מלאים (חיטה מלאה 5%), מלח, E-300, ברזל, ויטמינים B",
        "ingredients_list": ["קמח תירס מלא 85%", "סוכר", "דגנים מלאים (חיטה מלאה 5%)",
                              "מלח", "E-300", "ברזל", "ויטמינים B"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000011",
        "name_he": "קורנפלקס תלמה 500 גרם",
        "brand": "תלמה",
        "subtype": "cornflakes",
        "nutrition": {"energy_kcal": 380.0, "fat_g": 0.8, "fat_saturated_g": 0.15,
                      "fat_trans_g": 0.0, "sodium_mg": 520.0, "carbohydrates_g": 86.0,
                      "sugars_g": 7.5, "dietary_fiber_g": 2.5, "protein_g": 6.5},
        "ingredients_text_he": "קמח תירס 97%, סוכר, מלח, ויטמינים (B1, B2, B6, C, D), ברזל",
        "ingredients_list": ["קמח תירס 97%", "סוכר", "מלח", "ויטמינים (B1, B2, B6, C, D)", "ברזל"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7613031100001",
        "name_he": "קורנפלקס נסטלה 375 גרם",
        "brand": "נסטלה",
        "subtype": "cornflakes",
        "nutrition": {"energy_kcal": 378.0, "fat_g": 1.2, "fat_saturated_g": 0.2,
                      "fat_trans_g": 0.0, "sodium_mg": 490.0, "carbohydrates_g": 83.5,
                      "sugars_g": 8.5, "dietary_fiber_g": 3.5, "protein_g": 7.5},
        "ingredients_text_he": "קמח תירס, סוכר, מלח, E-300, ניאצין, ברזל, ריבופלאבין, תיאמין, B6",
        "ingredients_list": ["קמח תירס", "סוכר", "מלח", "E-300", "ניאצין",
                              "ברזל", "ריבופלאבין", "תיאמין", "B6"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "8437014100001",
        "name_he": "קורנפלקס אורגני ביו 300 גרם",
        "brand": "ביו",
        "subtype": "cornflakes",
        "nutrition": {"energy_kcal": 373.0, "fat_g": 1.0, "fat_saturated_g": 0.2,
                      "fat_trans_g": 0.0, "sodium_mg": 80.0, "carbohydrates_g": 83.0,
                      "sugars_g": 4.0, "dietary_fiber_g": 3.5, "protein_g": 7.2},
        "ingredients_text_he": "קמח תירס מלא 100%",
        "ingredients_list": ["קמח תירס מלא 100%"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.83, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },

    # -------------------------------------------------------------------------
    # SUBTYPE: kids_cereal
    # -------------------------------------------------------------------------
    {
        "barcode": "5054568100010",
        "name_he": "דגני בוקר קוקו פופס קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 388.0, "fat_g": 3.5, "fat_saturated_g": 1.5,
                      "fat_trans_g": 0.0, "sodium_mg": 330.0, "carbohydrates_g": 84.0,
                      "sugars_g": 35.0, "dietary_fiber_g": 3.0, "protein_g": 5.5},
        "ingredients_text_he": "עמילן תירס, סוכר, קקאו דל שומן 4.5%, סירופ גלוקוז, מלח, ויטמינים ומינרלים, צבע מאכל (E-150d), חומרי טעם וריח",
        "ingredients_list": ["עמילן תירס", "סוכר", "קקאו דל שומן 4.5%", "סירופ גלוקוז",
                              "מלח", "ויטמינים ומינרלים", "צבע מאכל (E-150d)", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן", "חלב"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.88, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7613031100010",
        "name_he": "דגני בוקר נסקוויק כדורי שוקולד נסטלה 375 גרם",
        "brand": "נסטלה",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 388.0, "fat_g": 3.2, "fat_saturated_g": 1.2,
                      "fat_trans_g": 0.0, "sodium_mg": 320.0, "carbohydrates_g": 83.5,
                      "sugars_g": 36.0, "dietary_fiber_g": 3.0, "protein_g": 6.0},
        "ingredients_text_he": "עמילן תירס, סוכר, קקאו מופחת שומן, שמן קנולה, סירופ גלוקוז-פרוקטוז, מלח, ויטמינים, חומרי טעם וריח",
        "ingredients_list": ["עמילן תירס", "סוכר", "קקאו מופחת שומן", "שמן קנולה",
                              "סירופ גלוקוז-פרוקטוז", "מלח", "ויטמינים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן", "חלב"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7613031100011",
        "name_he": "דגני בוקר שוקו-פיק נסטלה 375 גרם",
        "brand": "נסטלה",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 385.0, "fat_g": 3.0, "fat_saturated_g": 0.9,
                      "fat_trans_g": 0.0, "sodium_mg": 400.0, "carbohydrates_g": 82.0,
                      "sugars_g": 26.0, "dietary_fiber_g": 4.0, "protein_g": 7.5},
        "ingredients_text_he": "דגנים מלאים (חיטה מלאה 40%), קקאו מופחת שומן 8%, סוכר, שמן קנולה, מלח, ויטמינים ומינרלים, חומרי טעם וריח",
        "ingredients_list": ["דגנים מלאים (חיטה מלאה 40%)", "קקאו מופחת שומן 8%", "סוכר",
                              "שמן קנולה", "מלח", "ויטמינים ומינרלים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן", "חלב"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5054568100011",
        "name_he": "דגני בוקר סמאקס דבש קלוגס 330 גרם",
        "brand": "קלוגס",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 392.0, "fat_g": 2.5, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 280.0, "carbohydrates_g": 87.0,
                      "sugars_g": 38.0, "dietary_fiber_g": 2.0, "protein_g": 6.0},
        "ingredients_text_he": "עמילן חיטה, סוכר, דבש 4%, שמן קנולה, מלח, חומרי טעם וריח, ויטמינים ומינרלים",
        "ingredients_list": ["עמילן חיטה", "סוכר", "דבש 4%", "שמן קנולה",
                              "מלח", "חומרי טעם וריח", "ויטמינים ומינרלים"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5054568100012",
        "name_he": "דגני בוקר פרוט לופס קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 388.0, "fat_g": 4.0, "fat_saturated_g": 2.0,
                      "fat_trans_g": 0.0, "sodium_mg": 460.0, "carbohydrates_g": 85.0,
                      "sugars_g": 39.0, "dietary_fiber_g": 1.5, "protein_g": 5.5},
        "ingredients_text_he": "קמח תירס, קמח חיטה, סוכר, שמן קנולה, מלח, ויטמינים, צבע מאכל, חומרי טעם וריח",
        "ingredients_list": ["קמח תירס", "קמח חיטה", "סוכר", "שמן קנולה",
                              "מלח", "ויטמינים", "צבע מאכל", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7613031100012",
        "name_he": "דגני בוקר לייון נסטלה 400 גרם",
        "brand": "נסטלה",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 426.0, "fat_g": 10.0, "fat_saturated_g": 5.2,
                      "fat_trans_g": 0.0, "sodium_mg": 360.0, "carbohydrates_g": 76.0,
                      "sugars_g": 28.0, "dietary_fiber_g": 2.5, "protein_g": 5.0},
        "ingredients_text_he": "עמילן תירס, קקאו, סוכר, שמן קנולה, גלוקוז, לציטין סויה (E-322), מלח, ויטמינים, חומרי טעם וריח",
        "ingredients_list": ["עמילן תירס", "קקאו", "סוכר", "שמן קנולה", "גלוקוז",
                              "לציטין סויה (E-322)", "מלח", "ויטמינים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן", "חלב", "סויה"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000020",
        "name_he": "דגני בוקר טבעות שוקולד תלמה 375 גרם",
        "brand": "תלמה",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 385.0, "fat_g": 4.0, "fat_saturated_g": 1.5,
                      "fat_trans_g": 0.0, "sodium_mg": 350.0, "carbohydrates_g": 82.0,
                      "sugars_g": 30.0, "dietary_fiber_g": 3.0, "protein_g": 6.0},
        "ingredients_text_he": "עמילן תירס, סוכר, קקאו, שמן קנולה, מלח, צבע מאכל (E-150), חומרי טעם וריח, ויטמינים",
        "ingredients_list": ["עמילן תירס", "סוכר", "קקאו", "שמן קנולה", "מלח",
                              "צבע מאכל (E-150)", "חומרי טעם וריח", "ויטמינים"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.86, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5000159100001",
        "name_he": "דגני בוקר צ'יריוס דבש ואגוזים 375 גרם",
        "brand": "גנרל מילס",
        "subtype": "kids_cereal",
        "nutrition": {"energy_kcal": 381.0, "fat_g": 3.0, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 420.0, "carbohydrates_g": 80.0,
                      "sugars_g": 24.0, "dietary_fiber_g": 4.5, "protein_g": 7.5},
        "ingredients_text_he": "דגנים מלאים (שיבולת שועל מלאה 45%), סוכר, שמן קנולה, דבש 2%, מלח, ויטמינים, חומרי טעם וריח",
        "ingredients_list": ["דגנים מלאים (שיבולת שועל מלאה 45%)", "סוכר", "שמן קנולה",
                              "דבש 2%", "מלח", "ויטמינים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },

    # -------------------------------------------------------------------------
    # SUBTYPE: fitness_cereal
    # -------------------------------------------------------------------------
    {
        "barcode": "7613031100020",
        "name_he": "דגני בוקר פיטנס נסטלה 375 גרם",
        "brand": "נסטלה",
        "subtype": "fitness_cereal",
        "nutrition": {"energy_kcal": 381.0, "fat_g": 2.0, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 440.0, "carbohydrates_g": 79.0,
                      "sugars_g": 16.0, "dietary_fiber_g": 4.0, "protein_g": 8.0},
        "ingredients_text_he": "דגנים מלאים (חיטה מלאה 43%), עמילן תירס, סוכר, שמן קנולה, מלח, E-300, ניאצין, ברזל, B6, B2, B1",
        "ingredients_list": ["דגנים מלאים (חיטה מלאה 43%)", "עמילן תירס", "סוכר",
                              "שמן קנולה", "מלח", "E-300", "ניאצין", "ברזל", "B6", "B2", "B1"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": ["חלב"],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7613031100021",
        "name_he": "דגני בוקר פיטנס שוקולד נסטלה 375 גרם",
        "brand": "נסטלה",
        "subtype": "fitness_cereal",
        "nutrition": {"energy_kcal": 384.0, "fat_g": 3.5, "fat_saturated_g": 1.5,
                      "fat_trans_g": 0.0, "sodium_mg": 430.0, "carbohydrates_g": 78.0,
                      "sugars_g": 18.5, "dietary_fiber_g": 4.5, "protein_g": 8.5},
        "ingredients_text_he": "דגנים מלאים (חיטה מלאה 38%), עמילן תירס, קקאו 5%, סוכר, שמן קנולה, מלח, חומרי טעם וריח, ויטמינים",
        "ingredients_list": ["דגנים מלאים (חיטה מלאה 38%)", "עמילן תירס", "קקאו 5%",
                              "סוכר", "שמן קנולה", "מלח", "חומרי טעם וריח", "ויטמינים"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": ["חלב"],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5054568100020",
        "name_he": "דגני בוקר ספשל K קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "fitness_cereal",
        "nutrition": {"energy_kcal": 379.0, "fat_g": 1.0, "fat_saturated_g": 0.1,
                      "fat_trans_g": 0.0, "sodium_mg": 570.0, "carbohydrates_g": 78.5,
                      "sugars_g": 17.0, "dietary_fiber_g": 3.0, "protein_g": 13.5},
        "ingredients_text_he": "אורז מבושל 43%, חיטה מלאה 28%, סוכר, שמן קנולה, מלח, ויטמינים ומינרלים (E-300, ברזל, ניאצין, B6, B2, B1)",
        "ingredients_list": ["אורז מבושל 43%", "חיטה מלאה 28%", "סוכר", "שמן קנולה",
                              "מלח", "ויטמינים ומינרלים (E-300, ברזל, ניאצין, B6, B2, B1)"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.88, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5054568100021",
        "name_he": "דגני בוקר ספשל K פירות אדומים קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "fitness_cereal",
        "nutrition": {"energy_kcal": 377.0, "fat_g": 1.0, "fat_saturated_g": 0.1,
                      "fat_trans_g": 0.0, "sodium_mg": 560.0, "carbohydrates_g": 78.0,
                      "sugars_g": 18.5, "dietary_fiber_g": 3.0, "protein_g": 13.0},
        "ingredients_text_he": "אורז מבושל, חיטה מלאה, סוכר, חמוציות מיובשות 4%, שמן קנולה, מלח, חומרי טעם וריח, ויטמינים",
        "ingredients_list": ["אורז מבושל", "חיטה מלאה", "סוכר", "חמוציות מיובשות 4%",
                              "שמן קנולה", "מלח", "חומרי טעם וריח", "ויטמינים"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5054568100022",
        "name_he": "דגני בוקר אול-בראן פתיתי סובין קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "fitness_cereal",
        "nutrition": {"energy_kcal": 318.0, "fat_g": 3.5, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 450.0, "carbohydrates_g": 50.0,
                      "sugars_g": 16.0, "dietary_fiber_g": 28.0, "protein_g": 12.0},
        "ingredients_text_he": "סובין חיטה 75%, קמח חיטה מלא, סירופ גלוקוז, מלח, E-300, ניאצין, ברזל, B6, B2, B1",
        "ingredients_list": ["סובין חיטה 75%", "קמח חיטה מלא", "סירופ גלוקוז",
                              "מלח", "E-300", "ניאצין", "ברזל", "B6", "B2", "B1"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.88, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5011145100001",
        "name_he": "וויטביקס דגני בוקר חיטה מלאה 430 גרם",
        "brand": "וויטביקס",
        "subtype": "fitness_cereal",
        "nutrition": {"energy_kcal": 362.0, "fat_g": 2.0, "fat_saturated_g": 0.4,
                      "fat_trans_g": 0.0, "sodium_mg": 200.0, "carbohydrates_g": 71.0,
                      "sugars_g": 4.5, "dietary_fiber_g": 9.5, "protein_g": 11.5},
        "ingredients_text_he": "חיטה מלאה 95%, מלח, חומר מתפיח (E-500), ויטמין B2, ניאצין",
        "ingredients_list": ["חיטה מלאה 95%", "מלח", "חומר מתפיח (E-500)", "ויטמין B2", "ניאצין"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.86, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },

    # -------------------------------------------------------------------------
    # SUBTYPE: granola
    # -------------------------------------------------------------------------
    {
        "barcode": "7290100000028",
        "name_he": "גרנולה עם אגוזים ודבש טבעי 400 גרם",
        "brand": "לייף",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 440.0, "fat_g": 14.0, "fat_saturated_g": 2.5,
                      "fat_trans_g": 0.0, "sodium_mg": 200.0, "carbohydrates_g": 68.0,
                      "sugars_g": 18.0, "dietary_fiber_g": 6.5, "protein_g": 9.0},
        "ingredients_text_he": "שיבולת שועל מלאה 52%, דבש 8%, שמן חמניות, שקדים 7%, אגוזים 4%, זרעי חמניות, ונילין, מלח",
        "ingredients_list": ["שיבולת שועל מלאה 52%", "דבש 8%", "שמן חמניות", "שקדים 7%",
                              "אגוזים 4%", "זרעי חמניות", "ונילין", "מלח"],
        "allergens_contains": ["גלוטן", "אגוזים"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000029",
        "name_he": "גרנולה עם שבבי שוקולד 400 גרם",
        "brand": "לייף",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 460.0, "fat_g": 17.0, "fat_saturated_g": 5.5,
                      "fat_trans_g": 0.0, "sodium_mg": 220.0, "carbohydrates_g": 70.0,
                      "sugars_g": 24.0, "dietary_fiber_g": 5.5, "protein_g": 8.0},
        "ingredients_text_he": "שיבולת שועל מלאה, סוכר, שמן חמניות, שוקולד מריר 8%, קוקוס מגורר, ונילין, לציטין סויה (E-322), מלח",
        "ingredients_list": ["שיבולת שועל מלאה", "סוכר", "שמן חמניות", "שוקולד מריר 8%",
                              "קוקוס מגורר", "ונילין", "לציטין סויה (E-322)", "מלח"],
        "allergens_contains": ["גלוטן", "סויה"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000030",
        "name_he": "גרנולה חלבון עם חלבון מי גבינה 350 גרם",
        "brand": "פיט פוד",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 415.0, "fat_g": 12.0, "fat_saturated_g": 2.0,
                      "fat_trans_g": 0.0, "sodium_mg": 280.0, "carbohydrates_g": 53.0,
                      "sugars_g": 12.0, "dietary_fiber_g": 7.0, "protein_g": 19.0},
        "ingredients_text_he": "שיבולת שועל מלאה, חלבון מי גבינה 15%, דבש, שמן חמניות, שקדים, ממתיק (סוכרלוזה), ויטמינים, חומרי טעם וריח",
        "ingredients_list": ["שיבולת שועל מלאה", "חלבון מי גבינה 15%", "דבש", "שמן חמניות",
                              "שקדים", "ממתיק (סוכרלוזה)", "ויטמינים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן", "חלב", "אגוזים"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.83, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000031",
        "name_he": "גרנולה דייטס ללא תוספת סוכר 400 גרם",
        "brand": "לייף",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 430.0, "fat_g": 13.0, "fat_saturated_g": 2.0,
                      "fat_trans_g": 0.0, "sodium_mg": 80.0, "carbohydrates_g": 66.0,
                      "sugars_g": 10.0, "dietary_fiber_g": 7.5, "protein_g": 9.0},
        "ingredients_text_he": "שיבולת שועל מלאה 55%, ריבת תמרים 12%, שמן חמניות, שקדים, זרעי פשתן, קינמון, מלח",
        "ingredients_list": ["שיבולת שועל מלאה 55%", "ריבת תמרים 12%", "שמן חמניות",
                              "שקדים", "זרעי פשתן", "קינמון", "מלח"],
        "allergens_contains": ["גלוטן", "אגוזים"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.84, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000032",
        "name_he": "גרנולה עם חמוציות 400 גרם",
        "brand": "לייף",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 435.0, "fat_g": 13.5, "fat_saturated_g": 2.2,
                      "fat_trans_g": 0.0, "sodium_mg": 190.0, "carbohydrates_g": 69.0,
                      "sugars_g": 22.0, "dietary_fiber_g": 6.0, "protein_g": 8.5},
        "ingredients_text_he": "שיבולת שועל מלאה, סוכר קנים, שמן חמניות, חמוציות מיובשות 10%, שקדים, ונילין, מלח",
        "ingredients_list": ["שיבולת שועל מלאה", "סוכר קנים", "שמן חמניות",
                              "חמוציות מיובשות 10%", "שקדים", "ונילין", "מלח"],
        "allergens_contains": ["גלוטן", "אגוזים"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.84, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000033",
        "name_he": "גרנולה פצפוצים פריכים עם דבש ואגוזים 400 גרם",
        "brand": "תלמה",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 428.0, "fat_g": 12.0, "fat_saturated_g": 1.8,
                      "fat_trans_g": 0.0, "sodium_mg": 160.0, "carbohydrates_g": 70.0,
                      "sugars_g": 19.0, "dietary_fiber_g": 6.0, "protein_g": 8.0},
        "ingredients_text_he": "שיבולת שועל מלאה 58%, דבש 8%, שמן חמניות, שקדים 7%, אגוזי לוז 4%, מלח",
        "ingredients_list": ["שיבולת שועל מלאה 58%", "דבש 8%", "שמן חמניות",
                              "שקדים 7%", "אגוזי לוז 4%", "מלח"],
        "allergens_contains": ["גלוטן", "אגוזים"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000034",
        "name_he": "גרנולה זרעים עם שמן זית ודבש 350 גרם",
        "brand": "לייף",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 450.0, "fat_g": 18.0, "fat_saturated_g": 2.5,
                      "fat_trans_g": 0.0, "sodium_mg": 120.0, "carbohydrates_g": 55.0,
                      "sugars_g": 8.0, "dietary_fiber_g": 8.0, "protein_g": 11.0},
        "ingredients_text_he": "שיבולת שועל מלאה 45%, זרעי דלעת 15%, זרעי חמניות 12%, זרעי שומשום 8%, דבש 5%, שמן זית, מלח",
        "ingredients_list": ["שיבולת שועל מלאה 45%", "זרעי דלעת 15%", "זרעי חמניות 12%",
                              "זרעי שומשום 8%", "דבש 5%", "שמן זית", "מלח"],
        "allergens_contains": ["גלוטן", "שומשום"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "5054568100030",
        "name_he": "גרנולה קלאסטרס קלוגס 400 גרם",
        "brand": "קלוגס",
        "subtype": "granola",
        "nutrition": {"energy_kcal": 420.0, "fat_g": 11.0, "fat_saturated_g": 2.0,
                      "fat_trans_g": 0.0, "sodium_mg": 230.0, "carbohydrates_g": 71.0,
                      "sugars_g": 20.0, "dietary_fiber_g": 5.5, "protein_g": 8.0},
        "ingredients_text_he": "שיבולת שועל מלאה, סוכר, שמן קנולה, דבש, מלח, ונילין, לציטין סויה (E-322)",
        "ingredients_list": ["שיבולת שועל מלאה", "סוכר", "שמן קנולה", "דבש",
                              "מלח", "ונילין", "לציטין סויה (E-322)"],
        "allergens_contains": ["גלוטן", "סויה"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },

    # -------------------------------------------------------------------------
    # SUBTYPE: muesli
    # -------------------------------------------------------------------------
    {
        "barcode": "4016249100001",
        "name_he": "מוסלי שוויצרי קלאסי 500 גרם",
        "brand": "ברנבאום",
        "subtype": "muesli",
        "nutrition": {"energy_kcal": 371.0, "fat_g": 6.0, "fat_saturated_g": 1.0,
                      "fat_trans_g": 0.0, "sodium_mg": 30.0, "carbohydrates_g": 64.0,
                      "sugars_g": 12.0, "dietary_fiber_g": 8.0, "protein_g": 10.5},
        "ingredients_text_he": "שיבולת שועל מלאה 50%, שעורה מלאה 10%, חיטה מלאה 8%, אגוזי לוז 8%, זיזים 6%, ענבים מיובשים 10%, תפוחים מיובשים 8%",
        "ingredients_list": ["שיבולת שועל מלאה 50%", "שעורה מלאה 10%", "חיטה מלאה 8%",
                              "אגוזי לוז 8%", "זיזים 6%", "ענבים מיובשים 10%", "תפוחים מיובשים 8%"],
        "allergens_contains": ["גלוטן", "אגוזים"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.84, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "4016249100002",
        "name_he": "מוסלי בירכר בסיס 500 גרם",
        "brand": "ברנבאום",
        "subtype": "muesli",
        "nutrition": {"energy_kcal": 380.0, "fat_g": 7.5, "fat_saturated_g": 1.2,
                      "fat_trans_g": 0.0, "sodium_mg": 25.0, "carbohydrates_g": 62.0,
                      "sugars_g": 10.0, "dietary_fiber_g": 9.0, "protein_g": 11.0},
        "ingredients_text_he": "שיבולת שועל מלאה 60%, שעורה מלאה 15%, זרעי חמניות 10%, זרעי פשתן 8%, פירות יבשים מעורבים 7%",
        "ingredients_list": ["שיבולת שועל מלאה 60%", "שעורה מלאה 15%", "זרעי חמניות 10%",
                              "זרעי פשתן 8%", "פירות יבשים מעורבים 7%"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.84, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000038",
        "name_he": "מוסלי פירות ואגוזים 500 גרם",
        "brand": "תלמה",
        "subtype": "muesli",
        "nutrition": {"energy_kcal": 385.0, "fat_g": 8.5, "fat_saturated_g": 1.5,
                      "fat_trans_g": 0.0, "sodium_mg": 35.0, "carbohydrates_g": 63.0,
                      "sugars_g": 15.0, "dietary_fiber_g": 7.5, "protein_g": 10.0},
        "ingredients_text_he": "שיבולת שועל מלאה 45%, שעורה מלאה 10%, אגוזי לוז 8%, שקדים 6%, ענבים מיובשים 8%, משמשים מיובשים 6%, תמרים 5%, חיטה מלאה",
        "ingredients_list": ["שיבולת שועל מלאה 45%", "שעורה מלאה 10%", "אגוזי לוז 8%",
                              "שקדים 6%", "ענבים מיובשים 8%", "משמשים מיובשים 6%",
                              "תמרים 5%", "חיטה מלאה"],
        "allergens_contains": ["גלוטן", "אגוזים"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },

    # -------------------------------------------------------------------------
    # SUBTYPE: whole_grain_cereal
    # -------------------------------------------------------------------------
    {
        "barcode": "5054568100040",
        "name_he": "דגני בוקר פתיתי סובין קלוגס 375 גרם",
        "brand": "קלוגס",
        "subtype": "whole_grain_cereal",
        "nutrition": {"energy_kcal": 338.0, "fat_g": 3.0, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 500.0, "carbohydrates_g": 63.0,
                      "sugars_g": 16.0, "dietary_fiber_g": 15.0, "protein_g": 10.0},
        "ingredients_text_he": "סובין חיטה 48%, קמח חיטה מלא, סירופ גלוקוז, מלח, E-300, ניאצין, ברזל, B6, B2",
        "ingredients_list": ["סובין חיטה 48%", "קמח חיטה מלא", "סירופ גלוקוז",
                              "מלח", "E-300", "ניאצין", "ברזל", "B6", "B2"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.87, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "4013228100001",
        "name_he": "פתיתי כוסמין מלא 500 גרם",
        "brand": "ה'אנוטי",
        "subtype": "whole_grain_cereal",
        "nutrition": {"energy_kcal": 360.0, "fat_g": 2.5, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 10.0, "carbohydrates_g": 68.0,
                      "sugars_g": 2.0, "dietary_fiber_g": 9.5, "protein_g": 12.0},
        "ingredients_text_he": "כוסמין מלא 100%",
        "ingredients_list": ["כוסמין מלא 100%"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.83, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000041",
        "name_he": "דגני בוקר פתיתי דגנים מלאים מעורבים 375 גרם",
        "brand": "תלמה",
        "subtype": "whole_grain_cereal",
        "nutrition": {"energy_kcal": 365.0, "fat_g": 3.0, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 350.0, "carbohydrates_g": 71.0,
                      "sugars_g": 8.0, "dietary_fiber_g": 7.0, "protein_g": 10.0},
        "ingredients_text_he": "חיטה מלאה 35%, תירס מלא 20%, שיבולת שועל מלאה 15%, אורז מלא 10%, דגנים מלאים, סוכר, מלח, ויטמינים",
        "ingredients_list": ["חיטה מלאה 35%", "תירס מלא 20%", "שיבולת שועל מלאה 15%",
                              "אורז מלא 10%", "דגנים מלאים", "סוכר", "מלח", "ויטמינים"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.86, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000042",
        "name_he": "דגני בוקר פצפוצי חיטה מלאה 375 גרם",
        "brand": "תלמה",
        "subtype": "whole_grain_cereal",
        "nutrition": {"energy_kcal": 355.0, "fat_g": 2.0, "fat_saturated_g": 0.4,
                      "fat_trans_g": 0.0, "sodium_mg": 280.0, "carbohydrates_g": 71.0,
                      "sugars_g": 5.0, "dietary_fiber_g": 9.0, "protein_g": 11.0},
        "ingredients_text_he": "קמח חיטה מלא 95%, מלח, חומר מתפיח (E-500)",
        "ingredients_list": ["קמח חיטה מלא 95%", "מלח", "חומר מתפיח (E-500)"],
        "allergens_contains": ["גלוטן"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.86, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },

    # -------------------------------------------------------------------------
    # SUBTYPE: protein_cereal
    # -------------------------------------------------------------------------
    {
        "barcode": "5054568100050",
        "name_he": "דגני בוקר ספשל K חלבון קלוגס 320 גרם",
        "brand": "קלוגס",
        "subtype": "protein_cereal",
        "nutrition": {"energy_kcal": 383.0, "fat_g": 3.0, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 540.0, "carbohydrates_g": 66.0,
                      "sugars_g": 14.0, "dietary_fiber_g": 4.0, "protein_g": 20.0},
        "ingredients_text_he": "אורז מבושל, חלבון סויה 18%, חלבון מי גבינה 8%, סוכר, שמן קנולה, מלח, ויטמינים ומינרלים, חומרי טעם וריח",
        "ingredients_list": ["אורז מבושל", "חלבון סויה 18%", "חלבון מי גבינה 8%",
                              "סוכר", "שמן קנולה", "מלח", "ויטמינים ומינרלים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן", "חלב", "סויה"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.86, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7613031100050",
        "name_he": "דגני בוקר פיטנס חלבון נסטלה 320 גרם",
        "brand": "נסטלה",
        "subtype": "protein_cereal",
        "nutrition": {"energy_kcal": 380.0, "fat_g": 2.5, "fat_saturated_g": 0.5,
                      "fat_trans_g": 0.0, "sodium_mg": 520.0, "carbohydrates_g": 67.0,
                      "sugars_g": 12.0, "dietary_fiber_g": 5.0, "protein_g": 18.0},
        "ingredients_text_he": "דגנים מלאים (חיטה מלאה 30%), חלבון מי גבינה 15%, חלבון חיטה 8%, סוכר, שמן קנולה, ממתיק (סוכרלוזה), ויטמינים, חומרי טעם וריח",
        "ingredients_list": ["דגנים מלאים (חיטה מלאה 30%)", "חלבון מי גבינה 15%",
                              "חלבון חיטה 8%", "סוכר", "שמן קנולה", "ממתיק (סוכרלוזה)",
                              "ויטמינים", "חומרי טעם וריח"],
        "allergens_contains": ["גלוטן", "חלב"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.85, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
    {
        "barcode": "7290100000045",
        "name_he": "דגני בוקר חלבון מקסימום 27 גרם חלבון 300 גרם",
        "brand": "סינטק",
        "subtype": "protein_cereal",
        "nutrition": {"energy_kcal": 378.0, "fat_g": 3.5, "fat_saturated_g": 0.8,
                      "fat_trans_g": 0.0, "sodium_mg": 480.0, "carbohydrates_g": 62.0,
                      "sugars_g": 10.0, "dietary_fiber_g": 5.5, "protein_g": 22.0},
        "ingredients_text_he": "חלבון מי גבינה 25%, עמילן תירס, חלבון קזאין 10%, סוכר, שמן קנולה, ממתיק (סוכרלוזה), ויטמינים, חומרי טעם וריח, לציטין סויה",
        "ingredients_list": ["חלבון מי גבינה 25%", "עמילן תירס", "חלבון קזאין 10%",
                              "סוכר", "שמן קנולה", "ממתיק (סוכרלוזה)", "ויטמינים",
                              "חומרי טעם וריח", "לציטין סויה"],
        "allergens_contains": ["חלב", "סויה"],
        "allergens_may_contain": [],
        "ingredient_text_quality": "clean",
        "trust_score": 0.82, "trust_level": "high",
        "risk_flags": ["single_source_only"],
    },
]


def build_product_json(p: dict, idx: int) -> dict:
    barcode = p["barcode"]
    pid = f"bsip1_{barcode}"
    nn = p["nutrition"].copy()
    # Ensure all required fields exist (some products may lack cholesterol)
    if "cholesterol_mg" not in nn:
        nn["cholesterol_mg"] = None

    return {
        "schema_version": SCHEMA,
        "file_type": "product",
        "canonical_product_id": pid,
        "barcode": barcode,
        "canonical_name_he": p["name_he"],
        "canonical_name_en": None,
        "brand": p["brand"],
        "package_size_g": None,
        "unit_count": None,
        "unit_size_g": None,
        "serving_size_g": 30.0,
        "country_of_origin": None,
        "kosher_certification": None,
        "image_url": None,
        "source_retailers": [RETAILER],
        "normalized_nutrition_per_100g": nn,
        "energy_source_unit": "kcal",
        "ingredients_text_he": p["ingredients_text_he"],
        "ingredients_list": p["ingredients_list"],
        "allergens_contains": p["allergens_contains"],
        "allergens_may_contain": p["allergens_may_contain"],
        "claims": [],
        "confidence": {
            "identity_confidence": "high",
            "barcode_confidence": "confirmed",
            "nutrition_confidence": "confirmed_per_100g",
            "matched_by": "barcode_single_source",
            "observation_count": 1,
        },
        "barcode_validation_status": "retailer_confirmed",
        "barcode_confidence_reason": f"Scraped from Yohananof on {SCRAPE_DATE}.",
        "nutrition_basis_claimed": "ל100 גרם",
        "nutrition_basis_detected": "per_100g",
        "nutrition_consistency_status": "consistent",
        "nutrition_consistency_warnings": [],
        "ingredient_text_quality": p.get("ingredient_text_quality", "clean"),
        "ingredient_warnings": [],
        "canonical_trust_score": p.get("trust_score", 0.85),
        "canonical_trust_level": p.get("trust_level", "high"),
        "canonical_risk_flags": p.get("risk_flags", ["single_source_only"]),
        "conflicts_summary": {
            "count": 0, "has_unresolved": False,
            "fields_in_conflict": [], "identity_conflicts": [],
            "nutrition_conflicts": [], "ingredient_conflicts": [],
            "labeling_conflicts": [], "completeness_conflicts": [],
        },
        "missing_fields": [],
        "inferred_fields": [],
        "audit_ref": f"bsip1_audit_{barcode}.json",
        # Subtype tag for downstream tracking
        "bsip_cereal_subtype": p.get("subtype", "unknown"),
    }


def main():
    for idx, product in enumerate(PRODUCTS):
        data = build_product_json(product, idx)
        path = OUTPUT_DIR / f"bsip1_{product['barcode']}.json"
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Generated {len(PRODUCTS)} BSIP1 product files in {OUTPUT_DIR}")
    subtypes = {}
    for p in PRODUCTS:
        st = p.get("subtype", "unknown")
        subtypes[st] = subtypes.get(st, 0) + 1
    print("Subtype distribution:")
    for st, count in sorted(subtypes.items()):
        print(f"  {st}: {count}")


if __name__ == "__main__":
    main()
