#!/usr/bin/env python3
"""
generate_seo.py — derive seo.json (Bari SEO view, MVP)   (TASK-125)
==================================================================

Same philosophy as generate_dashboard.py: a derived, file-driven snapshot — no
cloud SDK, no DB, suitable for one operator. It ties each comparison page to the
category/launch state already tracked in command_center.json, and merges in
operator-maintained metrics from seo/metrics.json (your weekly Search Console /
Core Web Vitals export). It is OPERATIONAL: it flags pages that NEED ATTENTION
(live-but-not-indexed, weak ranking, failing CWV) rather than dumping vanity totals.

Run AFTER generate_dashboard.py (it reads command_center.json):
    cd C:\\Bari\\05_command_center
    python generate_dashboard.py && python generate_seo.py

Update cadence: WEEKLY. Search Console data lags ~2–3 days, so daily refreshes
create false urgency around stale numbers.
"""
import json
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
DASHBOARD = HERE / "command_center.json"
METRICS = HERE / "seo" / "metrics.json"
OUTPUT = HERE / "seo.json"

SEV = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}


def read_json(path, default):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return default


def page_attention(web_status, m):
    """Operational flags for one page (live-but-not-indexed / weak rank / CWV)."""
    out = []
    live = web_status in ("LIVE", "LEGACY")
    if live and m.get("indexed") is False:
        out.append(("CRITICAL", "live page is not indexed"))
    pos = m.get("position")
    if m.get("indexed") and (pos is None or pos > 20):
        out.append(("HIGH", f"weak ranking (position {pos if pos is not None else '—'})"))
    if (m.get("cwv") or {}).get("verdict") == "FAIL":
        out.append(("HIGH", "Core Web Vitals failing"))
    return out


def main():
    dash = read_json(DASHBOARD, {})
    if not dash:
        print("WARNING: command_center.json not found — run generate_dashboard.py first.")
    cats = dash.get("categories", [])
    metrics = read_json(METRICS, {})
    by_cat = metrics.get("by_category", {})

    pages, attn = [], []
    for c in cats:
        m = by_cat.get(c["id"], {})
        web_status = (c.get("website") or {}).get("status")
        flags = page_attention(web_status, m)
        page = {
            "category_id": c["id"],
            "name_he": c.get("name_he"),
            "name_en": c.get("name_en"),
            "route": (c.get("website") or {}).get("route"),
            "web_status": web_status,
            "launch_status": (c.get("launch") or {}).get("status"),
            "target_query": m.get("target_query"),
            "metrics": {
                "indexed": m.get("indexed"),
                "position": m.get("position"),
                "impressions": m.get("impressions"),
                "clicks": m.get("clicks"),
                "ctr": m.get("ctr"),
                "cwv": m.get("cwv"),
                "ai_visibility": m.get("ai_visibility"),
                "as_of": m.get("as_of"),
            },
            "attention": [{"severity": s, "message": msg} for s, msg in flags],
        }
        pages.append(page)
        for s, msg in flags:
            attn.append({"category_id": c["id"], "name_en": c.get("name_en"),
                         "severity": s, "message": msg})

    attn.sort(key=lambda a: SEV.get(a["severity"], 9))
    live = [p for p in pages if p["web_status"] in ("LIVE", "LEGACY")]
    tracked = [p for p in pages if p["metrics"]["indexed"] is not None]

    seo = {
        "_generated": True,
        "_do_not_edit": "Generated by generate_seo.py. Edit seo/metrics.json, then re-run.",
        "meta": {
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "sample": bool(metrics.get("sample", False)),
            "source_note": metrics.get("source_note", ""),
            "as_of": metrics.get("as_of"),
            "cadence": "weekly (Search Console lags ~2–3 days)",
        },
        "summary": {
            "pages_total": len(pages),
            "pages_live": len(live),
            "pages_tracked": len(tracked),
            "clicks": sum((p["metrics"]["clicks"] or 0) for p in pages),
            "impressions": sum((p["metrics"]["impressions"] or 0) for p in pages),
            "attention": len(attn),
        },
        "attention": attn,
        "pages": pages,
    }
    OUTPUT.write_text(json.dumps(seo, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"seo.json generated — {len(pages)} pages, {len(live)} live, "
          f"{len(attn)} attention item(s), sample={seo['meta']['sample']}")


if __name__ == "__main__":
    main()
