import type { Metadata } from "next";

import rawCorpus from "@/data/comparisons/hummus_frontend_v3.json";

import {
  loadComparisonCorpus,
  type ComparisonCorpusMeta,
  type ComparisonCorpusRaw,
} from "@/lib/comparisons/corpus";
import type { ComparisonCategoryPageData } from "@/lib/comparisons/registry/types";
import {
  filterHummusProducts,
  HUMMUS_SHELF_LENS_OPTIONS,
  type HummusShelfFilterId,
} from "@/lib/comparisons/hummus-shelf-filters";
import type { BariProductVM } from "@/lib/view-models";

export type HummusCorpusMeta = ComparisonCorpusMeta;

type HummusCorpusProduct = BariProductVM & {
  _product_type?: string;
};

// NOVA-1 single-ingredient whole/raw/frozen chickpea products. These score highly
// because they are minimally processed, but they are not comparable to prepared
// hummus spreads. Excluded from ranked display for v1.
// See excluded_products_hummus_v1.md for full audit record.
const EXCLUDED_NOVA1_IDS = new Set([
  "bsip1_7296073733324", // חומוס — 100% גרגרי חומוס, NOVA-1
  "bsip1_7296073733331", // חומוס ענק — גרגרי חומוס ענק, NOVA-1
  "bsip1_7296073005889", // חומוס לבן ענק שופרסל — NOVA-1
  "bsip1_7296073006015", // חומוס גדול שופרסל — NOVA-1
  "bsip1_3643820",       // חומוס ענק — NOVA-1
  "bsip1_7296073705505", // חומוס מוקפא — גרגרים קפואים, NOVA-1
]);

// TASK-087A category-boundary decision (implemented in TASK-087B): non-spread
// chickpea products that do not belong on the prepared ready-to-eat hummus-spread
// shelf. Two are canned/preserved whole chickpeas whose ingredient structure goes
// beyond a basic spread ("מבנה רכיבים מעובד — מעבר לממרח בסיסי"); two carry
// insufficient nutrition data and rendered an empty "score unavailable" state.
// All four are removed entirely from the comparison experience (rankings,
// comparison table, product count, grade tally and explanation layer).
const EXCLUDED_NON_SPREAD_IDS = new Set([
  "bsip1_7290018359686", // הקיסר חומוס ענק — חומוס שלם בשימור (לא ממרח)
  "bsip1_208428",        // חומוס שלם יכין — חומוס שלם בשימור (לא ממרח)
  "bsip1_7296073733317", // חומוס — נתוני תזונה חסרים, ציון לא זמין
  "bsip1_7296073733348", // חומוס ענק — נתוני תזונה חסרים, ציון לא זמין
]);

// Combined exclusion set applied to the ranked display. Both groups are removed
// for the same reason: they are not prepared ready-to-eat hummus spreads.
const EXCLUDED_PRODUCT_IDS = new Set([
  ...EXCLUDED_NOVA1_IDS,
  ...EXCLUDED_NON_SPREAD_IDS,
]);

// TASK-100: vegetable-spread product types are displayed on their own page
// (/hashvaot/vegetable-spreads). They are excluded here so the hummus page
// shows only hummus/legume-spread products (hummus_spread, masabacha).
const VEGETABLE_SPREAD_TYPES = new Set([
  "matbucha",
  "eggplant_spread",
  "pepper_spread",
]);

// TASK-086: generic grade-level fallback text was REMOVED. Per the BSIP2 → Web
// Translation Contract, a scored product must never rely on per-grade boilerplate
// such as "פרופיל הרכב טוב ביחס לקטגוריה". Each product now carries a
// product-specific insightLine plus deterministically-derived explanation arrays
// (positiveSignals / limitingFactors / unknowns / caveats) generated by
// build_hummus_explanation_v1.py from its BSIP2 trace. The UI renders those
// verbatim; this layer only strips the internal _product_type field.

function stripHummusInternalFields(products: HummusCorpusProduct[]): BariProductVM[] {
  return products
    .filter((product) => !EXCLUDED_PRODUCT_IDS.has(product.id))
    .filter((product) => !VEGETABLE_SPREAD_TYPES.has(product._product_type ?? ""))
    .map((product) => {
      const { _product_type, ...rest } = product;
      void _product_type;
      return rest;
    });
}

const loaded = loadComparisonCorpus(rawCorpus as unknown as ComparisonCorpusRaw);
const hummusCorpusMeta = loaded.meta;
const hummusProducts = stripHummusInternalFields(
  loaded.products as HummusCorpusProduct[]
);

export { hummusCorpusMeta, hummusProducts };

export const hummusMetadataLine = `${hummusProducts.length} מוצרים בדירוג · שופרסל, מאי 2026 · ממוין לפי ציון Bari`;

export const hummusHero = {
  eyebrow: "מנוע השוואה · חומוס",
  title: "חומוס: מה באמת יש במדף?",
} as const;

export const hummusPrologueSentences = [
  "בדקנו ממרחי חומוס ומסבחה הנמכרים בשופרסל — לפי הרכב המוצר, רשימת הרכיבים, סימוני האריזה ומבנה המוצר.",
  "הקטגוריה כוללת ממרחי חומוס ומסבחה בלבד. ממרחי ירקות (מטבוחה, חצילים, פלפלים) מוצגים בדף נפרד.",
  `כל ${hummusProducts.length} המוצרים המוצגים מקבלים ציון.`,
  "ערכי השומן אינם מוצגים בקטגוריה זו בשל מגבלות באיכות מקור הנתונים.",
] as const;

export const hummusMethodologyLines = [
  "הציון מחושב לפי מדדים מרובים: רמת עיבוד המוצר, נטל תוספי המזון, הרכב הערכים התזונתיים ומדדים נוספים הנוגעים למבנה המוצר.",
  "הציון הסופי הוא ממוצע משוקלל על סולם של 0 עד 100. ההשוואה היא קטגורית בלבד — כל מוצר מוערך ביחס לממרחי חומוס ומסבחה בלבד.",
  "ערכי השומן אינם מוצגים בקטגוריה זו בשל מגבלות באיכות מקור הנתונים.",
  "הדירוג נועד לעזור בהשוואה בין מוצרים ואינו מהווה המלצה תזונתית אישית.",
] as const;

export const hummusComparisonMetadata: Metadata = {
  title: "השוואת חומוס | Bari",
  description:
    "בדקנו ממרחי חומוס ומסבחה בשופרסל לפי הרכב המוצר, רשימת הרכיבים ומבנה המוצר.",
};

function isHummusShelfFilterId(filter: string): filter is HummusShelfFilterId {
  return HUMMUS_SHELF_LENS_OPTIONS.some((option) => option.id === filter);
}

const hummusShelfFilters = {
  lensOptions: HUMMUS_SHELF_LENS_OPTIONS,
  filterProducts: (products: BariProductVM[], activeFilters: string[]) =>
    filterHummusProducts(products, activeFilters.filter(isHummusShelfFilterId)),
};

export function getHummusPageData(): ComparisonCategoryPageData {
  return {
    products: hummusProducts,
    metadataLine: hummusMetadataLine,
    hero: hummusHero,
    prologueSentences: hummusPrologueSentences,
    methodologyLines: hummusMethodologyLines,
    corpusMeta: hummusCorpusMeta,
    shelfFilters: hummusShelfFilters,
  };
}

export function getHummusCorpusPayload(): {
  _meta: HummusCorpusMeta;
  products: BariProductVM[];
} {
  return {
    _meta: hummusCorpusMeta,
    products: hummusProducts,
  };
}
