import type { Metadata } from "next";

import rawCorpus from "@/data/comparisons/hummus_frontend_v4.json";

import {
  loadComparisonCorpus,
  type ComparisonCorpusMeta,
  type ComparisonCorpusRaw,
} from "@/lib/comparisons/corpus";
import type { ComparisonCategoryPageData } from "@/lib/comparisons/registry/types";
import {
  filterHummusProducts,
  HUMMUS_SHELF_LENS_OPTIONS,
  type HummusShelfFilterId,
} from "@/lib/comparisons/hummus-shelf-filters";
import type { BariProductVM } from "@/lib/view-models";

export type HummusCorpusMeta = ComparisonCorpusMeta;

type HummusCorpusProduct = BariProductVM & {
  _product_type?: string;
};

// NOVA-1 single-ingredient whole/raw/frozen chickpea products. These score highly
// because they are minimally processed, but they are not comparable to prepared
// hummus spreads. Excluded from ranked display for v1.
// See excluded_products_hummus_v1.md for full audit record.
const EXCLUDED_NOVA1_IDS = new Set([
  "bsip1_7296073733324", // חומוס — 100% גרגרי חומוס, NOVA-1
  "bsip1_7296073733331", // חומוס ענק — גרגרי חומוס ענק, NOVA-1
  "bsip1_7296073005889", // חומוס לבן ענק שופרסל — NOVA-1
  "bsip1_7296073006015", // חומוס גדול שופרסל — NOVA-1
  "bsip1_3643820",       // חומוס ענק — NOVA-1
  "bsip1_7296073705505", // חומוס מוקפא — גרגרים קפואים, NOVA-1
]);

// TASK-087A category-boundary decision (implemented in TASK-087B): non-spread
// chickpea products that do not belong on the prepared ready-to-eat hummus-spread
// shelf. Two are canned/preserved whole chickpeas whose ingredient structure goes
// beyond a basic spread ("מבנה רכיבים מעובד — מעבר לממרח בסיסי"); two carry
// insufficient nutrition data and rendered an empty "score unavailable" state.
// All four are removed entirely from the comparison experience (rankings,
// comparison table, product count, grade tally and explanation layer).
const EXCLUDED_NON_SPREAD_IDS = new Set([
  "bsip1_7290018359686", // הקיסר חומוס ענק — חומוס שלם בשימור (לא ממרח)
  "bsip1_208428",        // חומוס שלם יכין — חומוס שלם בשימור (לא ממרח)
  // bsip1_7296073733317 / bsip1_7296073733348 (insufficient-data חומוס,
  // "score unavailable") were scrubbed from hummus_frontend_v3.json (QA hygiene
  // 2026-06-02): removed from the corpus entirely, so no exclusion entry is needed.
]);

// TASK-137A (Nutrition ruling, 2026-06-01): RAW/DRY CHICKPEAS mis-tagged as
// `hummus_spread` that scored on partial data and slipped the NOVA-1 filter. The
// boundary test is NOT "has chickpeas" (every hummus does) and NOT "called סלט"
// (a tahini-based salad is still hummus). The test is whether it is a prepared,
// ready-to-eat spread. These two are unmistakably dry/raw chickpeas, not hummus:
// no ingredient list at all, no tahini, sodium ~12 mg (unsalted), energy 380 kcal
// (dry-legume range), protein 16.6 g. A prepared spread is salted (300–480 mg) and
// water/oil-diluted (250–290 kcal). Same class as EXCLUDED_NOVA1_IDS; removed for the
// same reason. Tahini-based salads/spreads (e.g. סלט חומוס) are KEPT — Product ruling.
const EXCLUDED_RAW_CHICKPEA_IDS = new Set([
  "bsip1_1990261", // חומוס — no ingredients, sodium 12mg, 380 kcal → dry/raw chickpeas
  "bsip1_3643714", // חומוס — duplicate of the above; same raw-chickpea signature
]);

// Combined exclusion set applied to the ranked display. All groups are removed
// for the same reason: they are not prepared ready-to-eat hummus spreads.
const EXCLUDED_PRODUCT_IDS = new Set([
  ...EXCLUDED_NOVA1_IDS,
  ...EXCLUDED_NON_SPREAD_IDS,
  ...EXCLUDED_RAW_CHICKPEA_IDS,
]);

// TASK-100: vegetable-spread product types are displayed on their own page
// (/hashvaot/vegetable-spreads). They are excluded here so the hummus page
// shows only hummus/legume-spread products (hummus_spread, masabacha).
const VEGETABLE_SPREAD_TYPES = new Set([
  "matbucha",
  "eggplant_spread",
  "pepper_spread",
]);

// TASK-086: generic grade-level fallback text was REMOVED. Per the BSIP2 → Web
// Translation Contract, a scored product must never rely on per-grade boilerplate
// such as "פרופיל הרכב טוב ביחס לקטגוריה". Each product now carries a
// product-specific insightLine plus deterministically-derived explanation arrays
// (positiveSignals / limitingFactors / unknowns / caveats) generated by
// build_hummus_explanation_v1.py from its BSIP2 trace. The UI renders those
// verbatim; this layer only strips the internal _product_type field.

function stripHummusInternalFields(products: HummusCorpusProduct[]): BariProductVM[] {
  return products
    .filter((product) => !EXCLUDED_PRODUCT_IDS.has(product.id))
    .filter((product) => !VEGETABLE_SPREAD_TYPES.has(product._product_type ?? ""))
    .map((product) => {
      const { _product_type, ...rest } = product;
      void _product_type;
      return rest;
    });
}

/**
 * Row surface enrichment. Surfaces the already-present protein value as a first-class metric.
 * The collapsed row's text is the authored insightLine sentence (TASK-167); the +/− positive
 * / limiting signals remain in the expansion. Display-only; not a score input.
 */
function enrichHummusRowSurface(products: BariProductVM[]): BariProductVM[] {
  return products.map((product) => ({
    ...product,
    metrics: { protein_g: product.expansion.nutrition?.protein ?? null },
    // Route the authored 2-line interpretive verdict (insightLine, TASK-168) to the rowVerdict
    // slot so the collapsed row renders it in full instead of single-line-truncated.
    rowVerdict: product.insightLine,
  }));
}

const loaded = loadComparisonCorpus(rawCorpus as unknown as ComparisonCorpusRaw);
const hummusCorpusMeta = loaded.meta;
const hummusProducts = enrichHummusRowSurface(
  stripHummusInternalFields(loaded.products as HummusCorpusProduct[])
);

export { hummusCorpusMeta, hummusProducts };

export const hummusMetadataLine = `${hummusProducts.length} מוצרים בדירוג · שופרסל, מאי 2026 · ממוין לפי ציון Bari`;

export const hummusHero = {
  eyebrow: "מנוע השוואה · חומוס",
  title: "חומוס: מה באמת יש במדף?",
} as const;

// TASK-137B: prologue rewritten to teach before it ranks — what we measured, how,
// and why protein is the headline metric (Product directive; rationale in
// 02_products/hummus/launch/hummus_salad_boundary_ruling_137A.md Part 3).
export const hummusPrologueSentences = [
  "בדקנו את ממרחי החומוס והמסבחה של שופרסל לפי מה שבאמת נמצא בקופסה — רשימת הרכיבים, רמת העיבוד, נטל תוספי המזון והרכב הערכים התזונתיים.",
  "כל מוצר מקבל ציון על סולם 0–100 ביחס לקטגוריה בלבד: חומוס נמדד מול חומוס, לא מול מזון אחר.",
  "בחזית כל מוצר בחרנו להציג את החלבון — ולא במקרה. חומוס הוא מקור החלבון הצמחי המרכזי במדף, וכמות החלבון מסגירה כמה גרגירי חומוס וטחינה יש בממרח באמת, לעומת מים ושמן שמדללים אותו.",
  "חלבון גבוה הוא לרוב הסימן לממרח מלא יותר — אבל זו הכותרת, לא כל הסיפור: הציון משקלל גם את רמת העיבוד, את מספר התוספים ואת ההרכב הכולל.",
] as const;

// IMP-6: the fat-data caveat is rendered ONCE, in the single header categoryNote slot —
// no longer duplicated across the prologue (former sentence 5) and the methodology
// footer. The protein-as-headline reasoning survives in prologue sentences 3–4.
// Upgraded to the cheese gold-standard format (bold header + explanatory paragraph) so the
// caveat reads consistently across all comparison categories. Factual content unchanged.
export const hummusCategoryNote =
  "הערת קטגוריה — ערכי שומן אינם מוצגים\n\nערכי השומן אינם מוצגים בקטגוריה זו בשל מגבלות באיכות מקור הנתונים. החלבון הוא לכן המספר האמין ביותר שאפשר להעמיד להשוואה — והוא גם מסגיר כמה גרגירי חומוס וטחינה יש בממרח באמת, לעומת מים ושמן שמדללים אותו.";

export const hummusMethodologyLines = [
  "הציון מחושב לפי מדדים מרובים: רמת עיבוד המוצר, נטל תוספי המזון, הרכב הערכים התזונתיים ומדדים נוספים הנוגעים למבנה המוצר.",
  "הציון הסופי הוא ממוצע משוקלל על סולם של 0 עד 100. ההשוואה היא קטגורית בלבד — כל מוצר מוערך ביחס לממרחי חומוס ומסבחה בלבד.",
  "הדירוג נועד לעזור בהשוואה בין מוצרים ואינו מהווה המלצה תזונתית אישית.",
] as const;

export const hummusComparisonMetadata: Metadata = {
  title: "השוואת חומוס | Bari",
  description:
    "בדקנו ממרחי חומוס ומסבחה בשופרסל לפי הרכב המוצר, רשימת הרכיבים ומבנה המוצר.",
};

function isHummusShelfFilterId(filter: string): filter is HummusShelfFilterId {
  return HUMMUS_SHELF_LENS_OPTIONS.some((option) => option.id === filter);
}

const hummusShelfFilters = {
  lensOptions: HUMMUS_SHELF_LENS_OPTIONS,
  filterProducts: (products: BariProductVM[], activeFilters: string[]) =>
    filterHummusProducts(products, activeFilters.filter(isHummusShelfFilterId)),
};

export function getHummusPageData(): ComparisonCategoryPageData {
  return {
    products: hummusProducts,
    metadataLine: hummusMetadataLine,
    hero: hummusHero,
    prologueSentences: hummusPrologueSentences,
    methodologyLines: hummusMethodologyLines,
    corpusMeta: hummusCorpusMeta,
    shelfFilters: hummusShelfFilters,
  };
}

export function getHummusCorpusPayload(): {
  _meta: HummusCorpusMeta;
  products: BariProductVM[];
} {
  return {
    _meta: hummusCorpusMeta,
    products: hummusProducts,
  };
}
