/** Stable, indexable public routes for sitemap generation. */
export const ALL_INDEXABLE_PATHS = [
  "/",
  "/catalog",
  "/hashvaot",
  "/hashvaot/bread",
  "/hashvaot/breakfast-cereals",
  "/hashvaot/brined-cheeses",
  "/hashvaot/cakes",
  "/hashvaot/cheese",
  "/hashvaot/chocolate-bars",
  "/hashvaot/chocolate-tablets",
  "/hashvaot/cookies-coffee",
  "/hashvaot/crackers",
  "/hashvaot/granola",
  "/hashvaot/hard-cheeses",
  "/hashvaot/hummus",
  "/hashvaot/juices",
  "/hashvaot/magnesium",
  "/hashvaot/milk-comparison",
  "/hashvaot/protein-bars",
  "/hashvaot/snacks",
  "/blog",
  "/blog/bread-analysis",
  "/blog/milk-analysis",
  "/blog/shemen-zayit",
  "/blog/sugar-alcohols",
  "/blog/food-dyes",
  "/research/glass-box",
  "/research/bread-transparency-shufersal",
  "/methodology",
  "/ai-index",
  "/privacy",
  "/terms",
] as const;
