/**
 * Realistic mock fixture for the Inventory Dashboard.
 * DEAD CODE: no longer imported — the admin dashboard now fetches live endpoints
 * (TASK 3 swap, 2026-07-01). Kept for reference; TypeScript still type-checks it.
 *
 * Category IDs corrected to match live ComparisonCategoryId registry union:
 *   bread | snacks | hummus | cheese | breakfast-cereals | granola
 *
 * comparisonHref: populated from the real registry routePath values (same source
 * as buildInventoryRows in loader.ts). Updated when InventoryProductRowVM gained
 * the comparisonHref field.
 */

import type {
  InventorySummaryVM,
  InventoryProductRowVM,
} from "@/lib/view-models";

export const MOCK_SUMMARY: InventorySummaryVM = {
  generatedAt: "2026-07-01T08:00:00.000Z",
  totalProducts: 214,
  categoryCount: 6,
  retailerBreakdown: [
    { id: "shufersal", nameHe: "שופרסל", count: 121 },
    { id: "yochananof", nameHe: "יוחננוף", count: 67 },
    { id: "other", nameHe: "מספר רשתות / אחר", count: 26 },
  ],
  topCategories: [
    { categoryId: "cheese", nameHe: "גבינות לבנות", count: 42, dominantGrade: "B" },
    { categoryId: "hummus", nameHe: "חומוס", count: 38, dominantGrade: "A" },
    { categoryId: "breakfast-cereals", nameHe: "דגני בוקר", count: 36, dominantGrade: "C" },
    { categoryId: "bread", nameHe: "לחם", count: 34, dominantGrade: "B" },
    { categoryId: "granola", nameHe: "גרנולה", count: 33, dominantGrade: "C" },
    { categoryId: "snacks", nameHe: "חטיפים מלוחים", count: 31, dominantGrade: "C" },
  ],
  gradeDistribution: {
    A: 28,
    B: 61,
    C: 74,
    D: 39,
    E: 6,
    unscored: 6,
  },
};

export const MOCK_PRODUCTS: InventoryProductRowVM[] = [
  {
    id: "chz-001",
    name: "גבינה צהובה 28%",
    brand: "תנובה",
    categoryId: "cheese",
    categoryNameHe: "גבינות לבנות",
    grade: "A",
    score: 81,
    confidence: "verified",
    retailer: { id: "shufersal", nameHe: "שופרסל" },
    sku: "7290000046527",
    imageUrl: null,
    comparisonHref: "/hashvaot/cheese",
  },
  {
    id: "chz-002",
    name: "גבינה עמק",
    brand: "תנובה",
    categoryId: "cheese",
    categoryNameHe: "גבינות לבנות",
    grade: "B",
    score: 74,
    confidence: "verified",
    retailer: { id: "shufersal", nameHe: "שופרסל" },
    sku: "7290000046534",
    imageUrl: null,
    comparisonHref: "/hashvaot/cheese",
  },
  {
    id: "chz-003",
    name: "גבינה בולגרית 5%",
    brand: null,
    categoryId: "cheese",
    categoryNameHe: "גבינות לבנות",
    grade: "B",
    score: 71,
    confidence: "partial",
    retailer: { id: "yochananof", nameHe: "יוחננוף" },
    sku: null,
    imageUrl: null,
    comparisonHref: "/hashvaot/cheese",
  },
  {
    id: "hms-001",
    name: "חומוס קלאסי",
    brand: "ויקטורי",
    categoryId: "hummus",
    categoryNameHe: "חומוס",
    grade: "A",
    score: 88,
    confidence: "verified",
    retailer: { id: "shufersal", nameHe: "שופרסל" },
    sku: "7290012345678",
    imageUrl: null,
    comparisonHref: "/hashvaot/hummus",
  },
  {
    id: "hms-002",
    name: "חומוס עם טחינה",
    brand: "אנגל",
    categoryId: "hummus",
    categoryNameHe: "חומוס",
    grade: "A",
    score: 84,
    confidence: "verified",
    retailer: { id: "yochananof", nameHe: "יוחננוף" },
    sku: "7290087654321",
    imageUrl: null,
    comparisonHref: "/hashvaot/hummus",
  },
  {
    id: "hms-003",
    name: "חומוס ביתי",
    brand: null,
    categoryId: "hummus",
    categoryNameHe: "חומוס",
    grade: "B",
    score: 68,
    confidence: "partial",
    retailer: { id: "other", nameHe: "מספר רשתות / אחר" },
    sku: null,
    imageUrl: null,
    comparisonHref: "/hashvaot/hummus",
  },
  {
    id: "cer-001",
    name: "קורנפלקס",
    brand: "קלוגס",
    categoryId: "breakfast-cereals",
    categoryNameHe: "דגני בוקר",
    grade: "C",
    score: 55,
    confidence: "verified",
    retailer: { id: "shufersal", nameHe: "שופרסל" },
    sku: "5000077610023",
    imageUrl: null,
    comparisonHref: "/hashvaot/breakfast-cereals",
  },
  {
    id: "cer-002",
    name: "שוקו פאפס",
    brand: "נסטלה",
    categoryId: "breakfast-cereals",
    categoryNameHe: "דגני בוקר",
    grade: "D",
    score: 38,
    confidence: "verified",
    retailer: { id: "shufersal", nameHe: "שופרסל" },
    sku: "7613035305397",
    imageUrl: null,
    comparisonHref: "/hashvaot/breakfast-cereals",
  },
  {
    id: "cer-003",
    name: "גרנולה בדבש",
    brand: "טבעול",
    categoryId: "granola",
    categoryNameHe: "גרנולה",
    grade: null,
    score: null,
    confidence: "insufficient",
    retailer: { id: "yochananof", nameHe: "יוחננוף" },
    sku: null,
    imageUrl: null,
    comparisonHref: "/hashvaot/granola",
  },
  {
    id: "brd-001",
    name: "לחם שאור כוסמין",
    brand: "אחי",
    categoryId: "bread",
    categoryNameHe: "לחם",
    grade: "A",
    score: 79,
    confidence: "verified",
    retailer: { id: "shufersal", nameHe: "שופרסל" },
    sku: "7290012781234",
    imageUrl: null,
    comparisonHref: "/hashvaot/bread",
  },
  {
    id: "brd-002",
    name: "לחם אחיד פרוס",
    brand: "ברמן",
    categoryId: "bread",
    categoryNameHe: "לחם",
    grade: "C",
    score: 52,
    confidence: "verified",
    retailer: { id: "other", nameHe: "מספר רשתות / אחר" },
    sku: "7290056781234",
    imageUrl: null,
    comparisonHref: "/hashvaot/bread",
  },
  {
    id: "snk-001",
    name: "בייגלה מלח ים",
    brand: "שטראוס",
    categoryId: "snacks",
    categoryNameHe: "חטיפים מלוחים",
    grade: "C",
    score: 58,
    confidence: "verified",
    retailer: { id: "shufersal", nameHe: "שופרסל" },
    sku: "7290000178323",
    imageUrl: null,
    comparisonHref: "/hashvaot/snacks",
  },
  {
    id: "snk-002",
    name: "פופקורן חמאה",
    brand: "עלית",
    categoryId: "snacks",
    categoryNameHe: "חטיפים מלוחים",
    grade: "E",
    score: 22,
    confidence: "verified",
    retailer: { id: "other", nameHe: "מספר רשתות / אחר" },
    sku: null,
    imageUrl: null,
    comparisonHref: "/hashvaot/snacks",
  },
];
