"""
Bari Category Factory QA Runner v1

Executes all automatable QA checks from category_factory_qa_v1.md against a
completed BSIP0→BSIP1 pipeline run and writes a Markdown report.

Usage:
    python run_qa.py --category hummus
    python run_qa.py --category hummus --retailer shufersal
    python run_qa.py --category hummus --bsip1-run run_hummus_001

Exit codes:
    0 — all checks pass (or warnings only)
    1 — one or more Hard Fail checks

Checks implemented (from category_factory_qa_v1_checklist.json):

  Traceability
    TRC-001  Every BSIP1 file has a populated source_retailers field
    TRC-002  Every BSIP1 barcode traces to a BSIP0 source file
    TRC-003  ingredients_raw_provenance.source is bsip0_scrape (Shufersal: known exception → WARN)
    TRC-004  BSIP0 source files have scraped_at and source_url

  Coverage
    COV-001  Nutrition coverage ≥ 80% (hard fail < 60%)
    COV-002  Ingredient list coverage ≥ 70% (hard fail < 50%)
    COV-003  Image URL coverage ≥ 90% (hard fail < 70%)
    COV-005  Sodium / sugar coverage (informational WARN)

  Canonical Structure
    CAN-001  canonical_bsip1/ exists and product count within 10% of BSIP0 approved
    CAN-003  schema_version consistent across all canonical files
    CAN-004  No excluded products leaked into canonical_bsip1/
    CAN-005  All canonical files have file_type = 'product'

  Regression
    REG-001  No BSIP2 scoring fields in canonical BSIP1 output
    REG-002  No frontend / view-model fields in canonical BSIP1 output
    REG-003  enrichment_version = approved version

Checks intentionally skipped (manual or fragile — see checklist):
    SCP-001  corpus_filter.md lock marker (manual file read)
    SCP-002  candidate_review.csv exists (included in CAN-004 path resolution)
    SCP-003  No OOS terms in approved corpus (category-specific term list required)
    SCP-004  Product count within expected range (threshold requires corpus_filter.md parsing)
    SCP-005  No multi-pack or catering-size products (weight_g not reliable from scraper)
    TRC-005  audit_ref file exists (audit files not yet generated by pipeline)
    COV-004  Barcode quality EAN-13 ratio (informational only)
    CAN-002  Manifest file exists (manifest not yet generated by pipeline — Wave 2)
    REG-004  No unexpected top-level fields (WARN only; bsip0_source is a known extra)
    REG-005  BSIP0 files unmodified (mtime checks fragile across OS copy operations)
"""

from __future__ import annotations

import argparse
import csv
import datetime
import json
import pathlib
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# ── Paths ──────────────────────────────────────────────────────────────────────
BARI_ROOT      = pathlib.Path(r"C:\Bari")
PRODUCTS_ROOT  = BARI_ROOT / "02_products"
OPS_ROOT       = BARI_ROOT / "03_operations"
BSIP1_OPS_ROOT = OPS_ROOT / "bsip1"
REPORTS_DIR    = OPS_ROOT / "qa" / "reports"

# ── Approved schema values ─────────────────────────────────────────────────────
APPROVED_SCHEMA_VERSION    = "bsip1_v0_1"
APPROVED_ENRICHMENT_VERSION = "bsip1_enrichment_v1"

BSIP2_FORBIDDEN_FIELDS = frozenset([
    "bsip2_score", "grade", "archetype", "nova_score", "score_trace",
    "dimension_scores", "bsip2_version", "concern_flags", "structural_emptiness",
    "satiety_score", "glycemic_score", "engineering_score", "nutritional_score",
    "metabolic_score", "floor_applied", "cap_applied", "trace_output",
    "final_score", "score_reason", "nova_proxy_result", "guardrail_caps",
    "archetype_module", "calorie_density_score",
])

FRONTEND_FORBIDDEN_FIELDS = frozenset([
    "display_name", "slug", "frontend_score", "view_model", "comparison_rank",
    "shelf_position", "insight_line", "explanation_text", "is_displayable",
    "display_score", "ui_label", "page_section", "frontend_confidence",
    "score_display", "grade_display", "comparison_context",
])

CORE_MACRO_FIELDS = ("energy_kcal", "protein_g", "carbohydrates_g", "fat_g")


# ── Result types ───────────────────────────────────────────────────────────────

class Check:
    """Accumulates findings for a single QA check."""

    def __init__(self, check_id: str, name: str, verdict_type: str = "hard_fail") -> None:
        self.id           = check_id
        self.name         = name
        self.verdict_type = verdict_type  # "hard_fail" | "warning" | "info"
        self.result       = "PASS"        # PASS | FAIL | WARN | SKIP
        self.total        = 0
        self.affected     = 0
        self.notes: list[str] = []
        self.affected_ids: list[str] = []

    def fail(self, note: str, pid: str = "") -> None:
        self.result = "FAIL"
        if note and note not in self.notes:
            self.notes.append(note)
        if pid:
            self.affected_ids.append(pid)
            self.affected += 1

    def warn(self, note: str, pid: str = "") -> None:
        if self.result != "FAIL":
            self.result = "WARN"
        if note and note not in self.notes:
            self.notes.append(note)
        if pid:
            self.affected_ids.append(pid)
            self.affected += 1

    def skip(self, reason: str) -> None:
        self.result = "SKIP"
        self.notes.append(reason)

    @property
    def is_hard_fail(self) -> bool:
        return self.result == "FAIL" and self.verdict_type == "hard_fail"

    @property
    def icon(self) -> str:
        return {"PASS": "OK", "FAIL": "FAIL", "WARN": "WARN", "SKIP": "SKIP"}[self.result]


# ── File loaders ───────────────────────────────────────────────────────────────

def _load_json_dir(directory: pathlib.Path, glob: str = "bsip1_*.json") -> list[tuple[pathlib.Path, dict]]:
    results = []
    for f in sorted(directory.glob(glob)):
        try:
            results.append((f, json.loads(f.read_text(encoding="utf-8"))))
        except Exception as e:
            results.append((f, {"_load_error": str(e)}))
    return results


def _load_bsip0_obs(obs_dir: pathlib.Path) -> list[tuple[pathlib.Path, dict]]:
    """Load BSIP0 P_*.json files (shufersal) excluding excluded dir and all_discovered."""
    return [
        (f, json.loads(f.read_text(encoding="utf-8")))
        for f in sorted(obs_dir.glob("P_*.json"))
        if "_excluded_bsip0" not in str(f) and "all_discovered" not in f.name
    ]


def _rejected_codes_from_csv(csv_path: pathlib.Path) -> set[str]:
    """Return set of codes/barcodes where approved_for_scrape != YES."""
    if not csv_path.exists():
        return set()
    codes: set[str] = set()
    with csv_path.open(encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("approved_for_scrape", "").strip().upper() != "YES":
                code = row.get("code", "") or row.get("barcode", "")
                if code:
                    # Shufersal codes are "P_XXXX" in the CSV; strip to bare barcode
                    # to match bsip1_{barcode}.json filenames in canonical_bsip1/
                    barcode = code.strip()
                    if barcode.startswith("P_"):
                        barcode = barcode[2:]
                    codes.add(barcode)
    return codes


# ── Individual checks ──────────────────────────────────────────────────────────

def check_trc001(bsip1_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """TRC-001: Every BSIP1 file has a populated source_retailers field."""
    chk = Check("TRC-001", "Every BSIP1 file has a populated source_retailers field")
    chk.total = len(bsip1_files)
    for path, rec in bsip1_files:
        if "_load_error" in rec:
            chk.fail(f"JSON load error: {rec['_load_error']}", path.stem)
            continue
        sr = rec.get("source_retailers")
        if not isinstance(sr, list) or len(sr) == 0:
            chk.fail(f"source_retailers is empty or absent", path.stem)
    return chk


def check_trc002(
    bsip1_files: list[tuple[pathlib.Path, dict]],
    obs_root: pathlib.Path,
) -> Check:
    """TRC-002: Every BSIP1 barcode traces to a BSIP0 source file."""
    chk = Check("TRC-002", "Every BSIP1 barcode traces to a BSIP0 source file")
    chk.total = len(bsip1_files)

    # Build the set of all known BSIP0 observation files/directories
    known_bsip0: set[str] = set()

    shufersal_dir = obs_root / "shufersal"
    if shufersal_dir.exists():
        for f in shufersal_dir.glob("P_*.json"):
            if "_excluded_bsip0" not in str(f) and "all_discovered" not in f.name:
                code = f.stem.replace("P_", "")
                known_bsip0.add(code)

    yohananof_dir = obs_root / "yohananof"
    if yohananof_dir.exists():
        for d in yohananof_dir.iterdir():
            if d.is_dir() and not d.name.startswith("_"):
                known_bsip0.add(d.name)

    for path, rec in bsip1_files:
        if "_load_error" in rec:
            chk.fail(f"JSON load error", path.stem)
            continue
        barcode = rec.get("barcode", "") or path.stem.replace("bsip1_", "")
        if barcode not in known_bsip0:
            chk.fail(
                f"No BSIP0 observation found for barcode {barcode}",
                path.stem,
            )
    return chk


def check_trc003(bsip1_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """TRC-003: ingredients_raw_provenance.source = bsip0_scrape.
    Shufersal exception: bsip1_text_fallback is a WARN (not hard fail) when
    ingredients_text_he is populated and source_retailers contains shufersal.
    """
    chk = Check("TRC-003", "ingredients_raw_provenance.source traceability")
    chk.total = len(bsip1_files)
    forbidden = {"manual", "llm_generated", "synthetic"}

    for path, rec in bsip1_files:
        if "_load_error" in rec:
            chk.fail("JSON load error", path.stem)
            continue
        ingr_list = rec.get("ingredients_list") or []
        if not ingr_list:
            continue  # no ingredients present — provenance check not applicable
        prov = rec.get("ingredients_raw_provenance") or {}
        source = prov.get("source")
        retailers = rec.get("source_retailers") or []
        has_ingr_text = bool(rec.get("ingredients_text_he"))

        if source == "bsip0_scrape":
            pass  # ideal — no action
        elif source in forbidden or source is None:
            chk.fail(
                f"provenance.source='{source}' (forbidden) for product with ingredients",
                path.stem,
            )
        elif source == "bsip1_text_fallback":
            if "shufersal" in retailers and has_ingr_text:
                chk.warn(
                    "provenance.source='bsip1_text_fallback' (Shufersal known exception — "
                    "ingredient text available via ingredients_text_he; see QA v1.1)",
                )
            else:
                chk.fail(
                    f"provenance.source='bsip1_text_fallback' without Shufersal retailer "
                    f"or missing ingredients_text_he",
                    path.stem,
                )
        else:
            chk.warn(f"Unrecognised provenance source: '{source}'", path.stem)
    return chk


def check_trc004(bsip0_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """TRC-004: BSIP0 source files have scraped_at and source_url."""
    chk = Check("TRC-004", "BSIP0 source files have scraped_at and source_url")
    chk.total = len(bsip0_files)
    for path, rec in bsip0_files:
        if "_load_error" in rec:
            chk.fail("JSON load error", path.stem)
            continue
        if not rec.get("scraped_at"):
            chk.fail("Missing scraped_at timestamp", path.stem)
        if not rec.get("source_url"):
            chk.fail("Missing source_url", path.stem)
    return chk


def check_cov001(bsip1_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """COV-001: Nutrition coverage ≥ 80% (hard fail < 60%)."""
    chk = Check("COV-001", "Nutrition coverage (energy+protein+carbs+fat ≥ 80%)")
    chk.total = len(bsip1_files)
    covered = 0
    for path, rec in bsip1_files:
        if "_load_error" in rec:
            continue
        nutr = rec.get("normalized_nutrition_per_100g") or {}
        if all(nutr.get(f) is not None for f in CORE_MACRO_FIELDS):
            covered += 1
    pct = (covered / chk.total * 100) if chk.total else 0
    chk.notes.append(f"{covered}/{chk.total} products have all 4 core macros ({pct:.1f}%)")
    if pct < 60:
        chk.fail(f"Nutrition coverage {pct:.1f}% < 60% hard-fail threshold")
    elif pct < 80:
        chk.warn(f"Nutrition coverage {pct:.1f}% is below 80% target")
    return chk


def check_cov002(bsip1_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """COV-002: Ingredient list coverage ≥ 70% (hard fail < 50%)."""
    chk = Check("COV-002", "Ingredient list coverage (ingredients_list non-empty ≥ 70%)")
    chk.total = len(bsip1_files)
    covered = sum(
        1 for _, rec in bsip1_files
        if not rec.get("_load_error") and rec.get("ingredients_list")
    )
    pct = (covered / chk.total * 100) if chk.total else 0
    chk.notes.append(f"{covered}/{chk.total} products have a non-empty ingredients_list ({pct:.1f}%)")
    if pct < 50:
        chk.fail(f"Ingredient coverage {pct:.1f}% < 50% hard-fail threshold")
    elif pct < 70:
        chk.warn(f"Ingredient coverage {pct:.1f}% is below 70% target")
    return chk


def check_cov003(bsip1_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """COV-003: Image URL coverage ≥ 90% (hard fail < 70%)."""
    chk = Check("COV-003", "Image URL coverage (image_url non-null ≥ 90%)")
    chk.total = len(bsip1_files)
    covered = sum(
        1 for _, rec in bsip1_files
        if not rec.get("_load_error") and rec.get("image_url")
    )
    pct = (covered / chk.total * 100) if chk.total else 0
    chk.notes.append(f"{covered}/{chk.total} products have image_url ({pct:.1f}%)")
    if pct < 70:
        chk.fail(f"Image coverage {pct:.1f}% < 70% hard-fail threshold")
    elif pct < 90:
        chk.warn(f"Image coverage {pct:.1f}% is below 90% target")
    return chk


def check_cov005(bsip1_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """COV-005: Sodium and sugar coverage (informational WARN)."""
    chk = Check("COV-005", "Sodium / sugar coverage (informational)", verdict_type="warning")
    chk.total = len(bsip1_files)
    valid = [rec for _, rec in bsip1_files if not rec.get("_load_error")]
    n = len(valid)
    sodium = sum(1 for r in valid if (r.get("normalized_nutrition_per_100g") or {}).get("sodium_mg") is not None)
    sugar  = sum(1 for r in valid if (r.get("normalized_nutrition_per_100g") or {}).get("sugars_g") is not None)
    sodium_pct = (sodium / n * 100) if n else 0
    sugar_pct  = (sugar  / n * 100) if n else 0
    chk.notes.append(f"sodium_mg: {sodium}/{n} ({sodium_pct:.1f}%) — target ≥ 60%")
    chk.notes.append(f"sugars_g:  {sugar}/{n}  ({sugar_pct:.1f}%)  — target ≥ 50%")
    if sodium_pct < 60:
        chk.warn(f"sodium_mg coverage {sodium_pct:.1f}% below 60% — may reduce BSIP2 red-label detection quality")
    if sugar_pct < 50:
        chk.warn(f"sugars_g coverage {sugar_pct:.1f}% below 50% — may reduce BSIP2 sugar-score quality")
    return chk


def check_can001(
    canonical_dir: pathlib.Path,
    bsip0_approved_count: int,
) -> Check:
    """CAN-001: canonical_bsip1 exists and product count ≥ 90% of BSIP0 approved."""
    chk = Check("CAN-001", "canonical_bsip1/ exists and is populated")
    if not canonical_dir.exists():
        chk.fail(f"Directory {canonical_dir} does not exist")
        return chk
    files = list(canonical_dir.glob("bsip1_*.json"))
    chk.total = bsip0_approved_count
    canonical_count = len(files)
    chk.notes.append(f"canonical_bsip1/ contains {canonical_count} files; BSIP0 approved = {bsip0_approved_count}")
    if canonical_count == 0:
        chk.fail("canonical_bsip1/ is empty")
    elif bsip0_approved_count > 0:
        floor = int(bsip0_approved_count * 0.90)
        if canonical_count < floor:
            chk.fail(
                f"canonical count {canonical_count} < 90% of BSIP0 approved {bsip0_approved_count} "
                f"(floor = {floor}) — check BSIP1 enrichment log for errors"
            )
        elif canonical_count < bsip0_approved_count:
            chk.warn(
                f"canonical count {canonical_count} is {bsip0_approved_count - canonical_count} "
                f"below BSIP0 approved count — within 10% tolerance"
            )
    return chk


def check_can003(canonical_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """CAN-003: schema_version consistent across all canonical files."""
    chk = Check("CAN-003", f"schema_version = '{APPROVED_SCHEMA_VERSION}' in all canonical files")
    chk.total = len(canonical_files)
    seen_versions: set[str] = set()
    for path, rec in canonical_files:
        if "_load_error" in rec:
            chk.fail("JSON load error", path.stem)
            continue
        sv = rec.get("schema_version")
        seen_versions.add(str(sv) if sv is not None else "ABSENT")
        if sv != APPROVED_SCHEMA_VERSION:
            chk.fail(f"schema_version = '{sv}' (expected '{APPROVED_SCHEMA_VERSION}')", path.stem)
    chk.notes.append(f"schema_version values found: {sorted(seen_versions)}")
    return chk


def check_can004(
    canonical_dir: pathlib.Path,
    rejected_codes: set[str],
) -> Check:
    """CAN-004: No excluded products leaked into canonical_bsip1/."""
    chk = Check("CAN-004", "No excluded products in canonical_bsip1/")
    chk.notes.append(f"{len(rejected_codes)} rejected codes from candidate_review.csv")
    if not canonical_dir.exists():
        chk.skip("canonical_bsip1/ directory does not exist — CAN-001 will report this")
        return chk
    for f in sorted(canonical_dir.glob("bsip1_*.json")):
        barcode = f.stem.replace("bsip1_", "")
        if barcode in rejected_codes:
            chk.fail(f"Excluded barcode {barcode} found in canonical_bsip1/", barcode)
    chk.total = len(list(canonical_dir.glob("bsip1_*.json")))
    return chk


def check_can005(canonical_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """CAN-005: All canonical files have file_type = 'product'."""
    chk = Check("CAN-005", "All canonical files have file_type = 'product'")
    chk.total = len(canonical_files)
    seen: set[str] = set()
    for path, rec in canonical_files:
        if "_load_error" in rec:
            chk.fail("JSON load error", path.stem)
            continue
        ft = rec.get("file_type")
        seen.add(str(ft) if ft is not None else "ABSENT")
        if ft != "product":
            chk.fail(f"file_type = '{ft}' (expected 'product')", path.stem)
    chk.notes.append(f"file_type values found: {sorted(seen)}")
    return chk


def _check_forbidden_fields(
    canonical_files: list[tuple[pathlib.Path, dict]],
    forbidden: frozenset[str],
    check_id: str,
    name: str,
) -> Check:
    chk = Check(check_id, name)
    chk.total = len(canonical_files)
    all_found: set[str] = set()
    for path, rec in canonical_files:
        if "_load_error" in rec:
            chk.fail("JSON load error", path.stem)
            continue
        hits = forbidden & rec.keys()
        if hits:
            all_found.update(hits)
            chk.fail(f"Forbidden fields: {sorted(hits)}", path.stem)
    if all_found:
        chk.notes.append(f"Forbidden fields found across corpus: {sorted(all_found)}")
    return chk


def check_reg001(canonical_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """REG-001: No BSIP2 scoring fields in canonical BSIP1 output."""
    return _check_forbidden_fields(
        canonical_files, BSIP2_FORBIDDEN_FIELDS,
        "REG-001", "No BSIP2 scoring fields in canonical BSIP1 output",
    )


def check_reg002(canonical_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """REG-002: No frontend / view-model fields in canonical BSIP1 output."""
    return _check_forbidden_fields(
        canonical_files, FRONTEND_FORBIDDEN_FIELDS,
        "REG-002", "No frontend / view-model fields in canonical BSIP1 output",
    )


def check_reg003(canonical_files: list[tuple[pathlib.Path, dict]]) -> Check:
    """REG-003: enrichment_version = approved version in all canonical files."""
    chk = Check("REG-003", f"enrichment_version = '{APPROVED_ENRICHMENT_VERSION}' in all canonical files")
    chk.total = len(canonical_files)
    seen: set[str] = set()
    for path, rec in canonical_files:
        if "_load_error" in rec:
            chk.fail("JSON load error", path.stem)
            continue
        ev = rec.get("enrichment_version")
        seen.add(str(ev) if ev is not None else "ABSENT")
        if ev != APPROVED_ENRICHMENT_VERSION:
            chk.fail(
                f"enrichment_version = '{ev}' (expected '{APPROVED_ENRICHMENT_VERSION}')",
                path.stem,
            )
    chk.notes.append(f"enrichment_version values found: {sorted(seen)}")
    return chk


# ── Report generator ───────────────────────────────────────────────────────────

def _pct(n: int, total: int) -> str:
    return f"{n}/{total} ({int(n / total * 100)}%)" if total else "0/0"


def generate_report(
    category: str,
    checks: list[Check],
    overall_pass: bool,
    run_ts: str,
) -> str:
    hard_fails = [c for c in checks if c.is_hard_fail]
    warnings   = [c for c in checks if c.result == "WARN"]
    passes     = [c for c in checks if c.result == "PASS"]
    skips      = [c for c in checks if c.result == "SKIP"]

    lines = [
        f"# QA Report — {category}",
        f"",
        f"**Generated:** {run_ts}",
        f"**Category:** {category}",
        f"**QA runner version:** run_qa.py v1",
        f"**Overall verdict:** {'PASS' if overall_pass else 'FAIL'}",
        f"",
        f"| Result | Count |",
        f"|--------|-------|",
        f"| PASS   | {len(passes)} |",
        f"| WARN   | {len(warnings)} |",
        f"| FAIL   | {len(hard_fails)} |",
        f"| SKIP   | {len(skips)} |",
        f"| Total  | {len(checks)} |",
        f"",
    ]

    if hard_fails:
        lines += [
            f"## Hard Fails — BSIP2 entry blocked",
            f"",
        ]
        for c in hard_fails:
            lines.append(f"### {c.id} — {c.name}")
            for note in c.notes:
                lines.append(f"- {note}")
            if c.affected_ids:
                sample = c.affected_ids[:10]
                suffix = f" (…and {len(c.affected_ids) - 10} more)" if len(c.affected_ids) > 10 else ""
                lines.append(f"- Affected products ({c.affected}): `{'`, `'.join(sample)}`{suffix}")
            lines.append("")

    if warnings:
        lines += [
            f"## Warnings — proceed with documented note",
            f"",
        ]
        for c in warnings:
            lines.append(f"### {c.id} — {c.name}")
            for note in c.notes:
                lines.append(f"- {note}")
            if c.affected_ids:
                sample = c.affected_ids[:10]
                suffix = f" (…and {len(c.affected_ids) - 10} more)" if len(c.affected_ids) > 10 else ""
                lines.append(f"- Affected products ({c.affected}): `{'`, `'.join(sample)}`{suffix}")
            lines.append("")

    lines += [
        f"## All Check Results",
        f"",
        f"| Check | Name | Result | Total | Affected |",
        f"|-------|------|--------|-------|----------|",
    ]
    for c in checks:
        lines.append(
            f"| {c.id} | {c.name} | {c.icon} | {c.total or '—'} | {c.affected or '—'} |"
        )

    lines += [
        f"",
        f"## Check Details",
        f"",
    ]
    for c in checks:
        lines.append(f"### {c.id} — {c.icon} — {c.name}")
        for note in c.notes:
            lines.append(f"- {note}")
        if c.affected_ids:
            sample = c.affected_ids[:20]
            suffix = f" (…and {len(c.affected_ids) - 20} more)" if len(c.affected_ids) > 20 else ""
            lines.append(f"- Affected ({c.affected}): `{'`, `'.join(sample)}`{suffix}")
        if not c.notes and not c.affected_ids:
            lines.append("- No issues found.")
        lines.append("")

    lines += [
        f"## Skipped Checks (manual or pipeline not yet ready)",
        f"",
        f"| Check | Reason |",
        f"|-------|--------|",
        f"| SCP-001 | corpus_filter.md lock marker — manual verification |",
        f"| SCP-002 | candidate_review.csv — covered by CAN-004 path resolution |",
        f"| SCP-003 | OOS term matching — requires category-specific term injection |",
        f"| SCP-004 | Count vs expected range — requires corpus_filter.md threshold parsing |",
        f"| SCP-005 | Multi-pack / catering size — weight_g unreliable from scraper |",
        f"| TRC-005 | audit_ref — audit files not yet generated by pipeline |",
        f"| COV-004 | Barcode quality ratio — informational only |",
        f"| CAN-002 | Manifest file — manifest generator not yet in pipeline (Wave 2) |",
        f"| REG-004 | Unexpected top-level fields — WARN only; bsip0_source is a known extra |",
        f"| REG-005 | BSIP0 mtime check — fragile across OS copy operations |",
        f"",
        f"---",
        f"",
        f"*Report generated by `run_qa.py` v1 — Bari Category Factory QA Runner*",
        f"*Reference: `03_operations/qa/category_factory_qa_v1.md`*",
    ]

    return "\n".join(lines)


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bari Category Factory QA Runner v1"
    )
    parser.add_argument("--category", required=True, help="Category slug, e.g. hummus")
    parser.add_argument(
        "--retailer",
        default="shufersal",
        help="Primary retailer for BSIP0 observations (default: shufersal)",
    )
    parser.add_argument(
        "--bsip1-run",
        dest="bsip1_run",
        default=None,
        help="BSIP1 run ID (default: run_{category}_001)",
    )
    args = parser.parse_args()

    category  = args.category
    retailer  = args.retailer
    run_id    = args.bsip1_run or f"run_{category}_001"
    run_ts    = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    # ── Resolve paths ──────────────────────────────────────────────────────────
    product_dir   = PRODUCTS_ROOT / category
    canonical_dir = product_dir / "canonical_bsip1"
    obs_root      = product_dir / "observations_bsip0"
    obs_retailer  = obs_root / retailer
    bsip1_run_dir = BSIP1_OPS_ROOT / run_id / "output"
    review_csv    = obs_retailer / "candidate_review.csv"

    print(f"Bari Category Factory QA Runner v1")
    print(f"Category : {category}")
    print(f"Retailer : {retailer}")
    print(f"BSIP1 run: {run_id}")
    print()

    # ── Check directories exist ────────────────────────────────────────────────
    path_issues = []
    if not product_dir.exists():
        path_issues.append(f"Product directory not found: {product_dir}")
    if not obs_retailer.exists():
        path_issues.append(f"BSIP0 observations not found: {obs_retailer}")
    if path_issues:
        for issue in path_issues:
            print(f"ERROR: {issue}")
        return 1

    # ── Load data ──────────────────────────────────────────────────────────────
    # BSIP1 run output (for TRC/COV checks)
    if bsip1_run_dir.exists():
        bsip1_run_files = _load_json_dir(bsip1_run_dir)
    else:
        print(f"WARN: BSIP1 run directory not found: {bsip1_run_dir}")
        print(f"      Falling back to canonical_bsip1/ for TRC/COV checks.")
        bsip1_run_files = _load_json_dir(canonical_dir) if canonical_dir.exists() else []

    canonical_files = _load_json_dir(canonical_dir) if canonical_dir.exists() else []

    bsip0_files = _load_bsip0_obs(obs_retailer)
    bsip0_approved_count = len(bsip0_files)

    rejected_codes = _rejected_codes_from_csv(review_csv)

    print(f"BSIP0 approved observations : {bsip0_approved_count}")
    print(f"BSIP1 run output files      : {len(bsip1_run_files)}")
    print(f"canonical_bsip1 files       : {len(canonical_files)}")
    print(f"Rejected codes from CSV     : {len(rejected_codes)}")
    print()

    # ── Run checks ─────────────────────────────────────────────────────────────
    checks: list[Check] = []

    print("Running checks ...")

    c = check_trc001(bsip1_run_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_trc002(bsip1_run_files, obs_root)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_trc003(bsip1_run_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_trc004(bsip0_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_cov001(bsip1_run_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_cov002(bsip1_run_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_cov003(bsip1_run_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_cov005(bsip1_run_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_can001(canonical_dir, bsip0_approved_count)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_can003(canonical_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_can004(canonical_dir, rejected_codes)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_can005(canonical_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_reg001(canonical_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_reg002(canonical_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    c = check_reg003(canonical_files)
    checks.append(c)
    print(f"  {c.id:8}  {c.icon}")

    # ── Verdict ────────────────────────────────────────────────────────────────
    hard_fails = [c for c in checks if c.is_hard_fail]
    warnings   = [c for c in checks if c.result == "WARN"]
    overall_pass = len(hard_fails) == 0

    print()
    print(f"{'='*50}")
    print(f"PASS: {sum(1 for c in checks if c.result == 'PASS')}  "
          f"WARN: {len(warnings)}  "
          f"FAIL: {len(hard_fails)}  "
          f"SKIP: {sum(1 for c in checks if c.result == 'SKIP')}")
    print()
    if overall_pass:
        print(f"VERDICT: PASS — {category} is clear for BSIP2 entry")
        if warnings:
            print(f"         ({len(warnings)} warning(s) — see report for details)")
    else:
        print(f"VERDICT: FAIL — {len(hard_fails)} Hard Fail(s) must be resolved before BSIP2")
        for c in hard_fails:
            print(f"  * {c.id}: {c.name}")
    print(f"{'='*50}")

    # ── Write report ───────────────────────────────────────────────────────────
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / f"qa_report_{category}.md"
    report_text = generate_report(category, checks, overall_pass, run_ts)
    report_path.write_text(report_text, encoding="utf-8")
    print(f"\nReport: {report_path}")

    return 0 if overall_pass else 1


if __name__ == "__main__":
    sys.exit(main())
